using CESDK.SourceGenerators.EngineApi.Tests.Infrastructure;

namespace CESDK.SourceGenerators.EngineApi.Tests.Generator;

/// <summary>The generated text for the nominal spec file, and that it compiles clean against the real SDK.</summary>
public sealed class EmissionTests(RoslynFixture roslyn) : IClassFixture<RoslynFixture>
{
    [Fact]
    public void Nominal_spec_emits_one_file_with_the_namespace_type_cache_fields_and_four_wrappers()
    {
        var run = roslyn.Run("memory-scalars.cesdk-api.txt", SpecSources.Memory);

        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;

        Assert.StartsWith("// <auto-generated/>\n#nullable enable\n", text, StringComparison.Ordinal);
        Assert.Contains("namespace Demo.Engine.Generated", text, StringComparison.Ordinal);
        Assert.Contains("public static partial class MemoryScalars", text, StringComparison.Ordinal);
        Assert.Contains("private static readonly global::CESDK.Lua.References.LuaRef s_luaGlobal_readInteger = new();",
            text,
            StringComparison.Ordinal);
        Assert.Contains("private static readonly global::CESDK.Lua.References.LuaRef s_luaGlobal_writeQword = new();",
            text,
            StringComparison.Ordinal);

        // Every entry declares an 'address' argument, so each gets the two-method split (Emit/EngineApiFileEmitter.cs,
        // EmitAddressTypedWrapper): a private nuint core (LuaGlobalCallEmitter's own call shape, untouched) plus a
        // public wrapper typed with CESDK.Engine.Values.Address. A CE-side address is a ulong, not a nuint, so the
        // public surface never exposes the nuint-typed parameter.
        Assert.Contains("private static bool __TryReadInt32Raw(nuint address, out int value)", text,
            StringComparison.Ordinal);
        Assert.Contains("public static bool TryReadInt32(global::CESDK.Engine.Values.Address address, out int value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("private static bool __TryReadInt64Raw(nuint address, out long value)", text,
            StringComparison.Ordinal);
        Assert.Contains("public static bool TryReadInt64(global::CESDK.Engine.Values.Address address, out long value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("private static bool __WriteInt32Raw(nuint address, int value)", text,
            StringComparison.Ordinal);
        Assert.Contains("public static bool WriteInt32(global::CESDK.Engine.Values.Address address, int value)", text,
            StringComparison.Ordinal);
        Assert.Contains("private static bool __WriteInt64Raw(nuint address, long value)", text,
            StringComparison.Ordinal);
        Assert.Contains("public static bool WriteInt64(global::CESDK.Engine.Values.Address address, long value)", text,
            StringComparison.Ordinal);
        Assert.Contains("[global::System.CodeDom.Compiler.GeneratedCode(\"CESDK.SourceGenerators.EngineApi\",", text,
            StringComparison.Ordinal);
        Assert.DoesNotContain("partial bool", text,
            StringComparison.Ordinal); // complete declarations, never a partial-method body
        Assert.Contains("global::CESDK.Lua.Marshalling.BooleanMarshaller.Push(__L, true);", text,
            StringComparison.Ordinal);
        Assert.Contains("if (!__L.TryCall(2, 1).IsOk)", text, StringComparison.Ordinal);
    }

    [Fact]
    public void The_try_form_body_matches_the_documented_call_shape_exactly()
    {
        var run = roslyn.Run("single.cesdk-api.txt", SpecSources.SingleTry);
        run.AssertCompilesClean();

        // The private core: byte-for-byte the shape LuaGlobalCallEmitter produces, just renamed and
        // made private by EmitAddressTypedWrapper.
        var expectedCore = """
                           private static bool __TryReadInt32Raw(nuint address, out int value)
                           {
                               global::CESDK.Lua.State.LuaState __L = global::CESDK.Lua.Runtime.LuaRuntime.AcquireState();
                               int __top = __L.Top;
                               try
                               {
                                   if (!global::CESDK.Lua.CompilerServices.LuaGlobalFunctions.TryPush(__L, s_luaGlobal_readInteger, "readInteger"u8))
                                   {
                                       return global::CESDK.Lua.CompilerServices.LuaCallSupport.Fail(__L, __top, out value);
                                   }

                                   global::CESDK.Lua.Marshalling.AddressMarshaller.Push(__L, address);
                                   if (!__L.TryCall(1, 1).IsOk)
                                   {
                                       return global::CESDK.Lua.CompilerServices.LuaCallSupport.Fail(__L, __top, out value);
                                   }

                                   bool __ok = global::CESDK.Lua.Marshalling.Int32Marshaller.TryRead(__L, -1, out value);
                                   return __ok;
                               }
                               catch (global::CESDK.Lua.Calls.LuaException)
                               {
                                   value = default;
                                   return false;
                               }
                               finally
                               {
                                   __L.SetTop(__top);
                               }
                           }
                           """;
        Assert.Contains(Indented(expectedCore), run.SingleGeneratedText, StringComparison.Ordinal);

        // The public wrapper: the only new code, a two-line boundary conversion.
        var expectedWrapper = """
                              public static bool TryReadInt32(global::CESDK.Engine.Values.Address address, out int value)
                              {
                                  return __TryReadInt32Raw(unchecked((nuint)address.ToUInt64()), out value);
                              }
                              """;
        Assert.Contains(Indented(expectedWrapper), run.SingleGeneratedText, StringComparison.Ordinal);
    }

    [Fact]
    public void Two_forms_of_the_same_global_declare_one_cache_field_and_two_methods()
    {
        var run = roslyn.Run("shared.cesdk-api.txt", SpecSources.SharedGlobal);
        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;

        Assert.Equal(1, CountOccurrences(text, "s_luaGlobal_readInteger = new();"));
        Assert.Contains("public static bool TryReadInt32(global::CESDK.Engine.Values.Address address, out int value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("public static int ReadInt32(global::CESDK.Engine.Values.Address address)", text,
            StringComparison.Ordinal);
    }

    [Fact]
    public void The_global_namespace_is_emitted_without_a_namespace_block()
    {
        const string Text = """
                            namespace:
                            type: Root

                            global: readInteger
                            method: TryReadInt32
                            form: try
                            arg: address:address
                            result: value:int32
                            doc: Reads an integer.
                            """;

        var run = roslyn.Run("root.cesdk-api.txt", Text);
        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;

        Assert.DoesNotContain("namespace ", text, StringComparison.Ordinal);
        Assert.Contains("public static partial class Root", text, StringComparison.Ordinal);
    }

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        var index = 0;
        while ((index = text.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }

        return count;
    }

    // The method sits two levels deep (namespace, then the partial class): 8 spaces, SourceWriter's convention.
    private static string Indented(string text)
    {
        return string.Join('\n',
            text.ReplaceLineEndings("\n").Split('\n')
                .Select(static line => line.Length > 0 ? "        " + line : line));
    }
}
