using System.Globalization;
using System.Text;

using CheatEngine.SDK.SourceGenerators.LuaBridgeContract.Catalog;

using Microsoft.CodeAnalysis.Text;

namespace CheatEngine.SDK.SourceGenerators.LuaBridgeContract.Emit;

/// <summary>Emits the allocation-free managed operation selector consumed by the protected bridge P/Invoke wrapper.</summary>
internal static class LuaProtectedOperationEmitter
{
	public const string HintName = "CheatEngine.SDK.Lua.Interop.Protected.LuaProtectedOperation.g.cs";

	public static SourceText Emit(CatalogModel catalog)
	{
		StringBuilder text = new();
		text.AppendLine("// <auto-generated/>");
		text.AppendLine("#nullable enable");
		text.AppendLine();
		text.AppendLine("namespace CheatEngine.SDK.Lua.Interop.Protected;");
		text.AppendLine();
		text.AppendLine(
			"// Values are the C11 operation numbers. They are generated from protected-operations.json; changing an opcode changes the ABI.");
		text.AppendLine("internal enum LuaProtectedOperation");
		text.AppendLine("{");
		for (int i = 0; i < catalog.Operations.Length; i++)
		{
			CatalogOperation operation = catalog.Operations[i];
			text.Append("    ").Append(operation.Id).Append(" = ")
				.Append(operation.Opcode.ToString(CultureInfo.InvariantCulture));
			text.AppendLine(i == catalog.Operations.Length - 1 ? string.Empty : ",");
		}

		text.AppendLine("}");
		text.AppendLine();
		text.AppendLine(
			"// The bitmap mirrors the native C11 contract and supports sparse opcode assignments without an enum-order assumption.");
		text.AppendLine("internal static class LuaProtectedOperationContract");
		text.AppendLine("{");
		text.Append("    internal const int Count = ")
			.Append(catalog.Operations.Length.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
		text.Append("    internal const ulong RequiredBitmap = 0x")
			.Append(catalog.RequiredBitmap.ToString("X16", CultureInfo.InvariantCulture)).AppendLine("UL;");
		text.AppendLine();
		text.AppendLine("    internal static bool IsDefined(LuaProtectedOperation operation)");
		text.AppendLine("    {");
		text.AppendLine("        var opcode = (uint)operation;");
		text.AppendLine("        return opcode < 64 && (RequiredBitmap & (1UL << (int)opcode)) != 0;");
		text.AppendLine("    }");
		text.AppendLine("}");

		return SourceText.From(text.ToString(), Encoding.UTF8);
	}
}
