#Requires -Version 7.0
<#
.SYNOPSIS
    First stage of the newest-SDK canary: writes the newest .NET SDK of the pinned channel into global.json.

.DESCRIPTION
    global.json pins the SDK exactly (rollForward: disable), and the lock files record the implicit packages of that SDK
    (ILLink, ILCompiler). The canary tells ahead of a Dependabot dotnet-sdk pull request what the next SDK changes.
    This stage runs BEFORE the composite setup action, which installs the SDK that global.json names, so it uses no
    .NET CLI at all:

    1. Read sdk.version of global.json and derive its channel (10.0.401 -> 10.0).
    2. Take -SdkVersion, or latest-sdk of the channel's release metadata
       (https://builds.dotnet.microsoft.com/dotnet/release-metadata/<channel>/releases.json).
    3. Rewrite sdk.version, and the pinned version where errorMessage names it (the Release tests of the canary include
       ToolchainPinTests, which require errorMessage to name the selected SDK and its install command), keeping
       rollForward, allowPrerelease and the test runner section: removing global.json would also drop
       "test": { "runner": "Microsoft.Testing.Platform" } and put the test command in VSTest mode.
       https://learn.microsoft.com/dotnet/core/tools/global-json
    4. Write pinned-version, sdk-version and changed to GITHUB_OUTPUT, and a line to the job summary.

    The rewrite happens in the CI runner's checkout (or a throwaway local clone): never commit it. A new SDK reaches the
    repository through the dotnet-sdk Dependabot pull request, with the lock files regenerated by eng/Update-LockFiles.ps1.

.PARAMETER SdkVersion
    Use this full SDK version (for example 10.0.402) instead of the channel's latest-sdk.

.PARAMETER GlobalJsonPath
    The global.json to rewrite. Defaults to the repository's.

.EXAMPLE
    ./eng/ci/health/Set-CanarySdkVersion.ps1
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $SdkVersion,
    [string] $GlobalJsonPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath 'HealthCheck.psm1') -Force
Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath 'HealthCommand.psm1') -Force

if (-not $GlobalJsonPath) {
    $GlobalJsonPath = Join-Path -Path (Get-HealthRepositoryRoot) -ChildPath 'global.json'
}

$json = Get-Content -Raw -LiteralPath $GlobalJsonPath
$pinned = [string] ($json | ConvertFrom-Json -AsHashtable)['sdk']['version']
$channel = Get-SdkChannel -Version $pinned

if ($SdkVersion) {
    $newest = $SdkVersion
    if ((Get-SdkChannel -Version $newest) -cne $channel) {
        throw "-SdkVersion $newest is not on the $channel channel of global.json ($pinned); a new major is a migration, not a canary."
    }
}
else {
    $metadataUrl = "https://builds.dotnet.microsoft.com/dotnet/release-metadata/$channel/releases.json"
    Write-Host "Reading the newest SDK of channel $channel from $metadataUrl."
    $metadata = Invoke-WebRequest -Uri $metadataUrl -MaximumRetryCount 3 -RetryIntervalSec 5 -UseBasicParsing
    $newest = Get-NewestSdkVersion -ReleasesJson ([string] $metadata.Content) -Channel $channel
}

$changed = $newest -cne $pinned
if ($changed -and $PSCmdlet.ShouldProcess($GlobalJsonPath, "Set sdk.version (and its errorMessage mentions) to $newest")) {
    $rewritten = Get-UpdatedGlobalJson -Json $json -Version $newest
    [System.IO.File]::WriteAllText($GlobalJsonPath, $rewritten + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

Write-HealthOutput -Value ([ordered]@{
        'pinned-version' = $pinned
        'sdk-version'    = $newest
        'changed'        = $(if ($changed) { 'true' } else { 'false' })
    })
$line = if ($changed) {
    "SDK canary: global.json now selects $newest (pinned: $pinned) for this run only."
}
else {
    "SDK canary: the newest SDK of channel $channel is the pinned SDK $pinned; the canary rebuilds with it."
}

Write-HealthSummary -Line @('## Newest .NET SDK canary', '', $line, '')
