namespace CheatEngine.SDK.SourceGenerators.LuaBindings.Tests.Infrastructure;

/// <summary>
///     The exact files expected for the two nominal sources, written by hand rather than through the emitter. Line
///     endings are normalised to <c>\n</c> because the generator always writes <c>\n</c> while this repository
///     checks out as CRLF; the tool name and version come from the generator assembly.
/// </summary>
internal static class ExpectedFiles
{
    /// <summary>Hint name of the file for <see cref="BindingSources.Functions" />.</summary>
    public const string FunctionsHintName = "Demo.Functions.LuaFunctions.g.cs";

    /// <summary>Hint name of the file for <see cref="BindingSources.Globals" />.</summary>
    public const string GlobalsHintName = "Demo.Memory.LuaGlobals.g.cs";

    private static readonly string GeneratedCode = CreateGeneratedCodeLine();

    private static readonly string FunctionsText = Normalise($$"""
                                                               // <auto-generated/>
                                                               #nullable enable

                                                               #pragma warning disable CS0612, CS0618 // a [LuaFunction] target may be marked [Obsolete]

                                                               namespace Demo
                                                               {
                                                                   partial class Functions
                                                                   {
                                                                       /// <summary>
                                                                       /// Registers every <c>[LuaFunction]</c> of this type as a global of <paramref name="state"/>: <c>add</c>, <c>greet</c>.
                                                                       /// Stack: +0 on success; +1 (the error value) on failure, as for every protected operation.
                                                                       /// </summary>
                                                                       /// <param name="state">The state to register on; the calling thread's. Requires the plugin to be enabled.</param>
                                                                       /// <returns>The status of the first failing operation, or <c>LuaStatus.Ok</c>.</returns>
                                                                       {{GeneratedCode}}
                                                                       public static unsafe global::CheatEngine.SDK.Lua.Calls.LuaStatus RegisterLuaFunctions(global::CheatEngine.SDK.Lua.State.LuaState state)
                                                                       {
                                                                           global::CheatEngine.SDK.Lua.Calls.LuaStatus __status;
                                                                           __status = state.TryPushFunction(new global::CheatEngine.SDK.Lua.Callbacks.LuaNativeFunction(&__LuaThunk_add));
                                                                           if (!__status.IsOk)
                                                                           {
                                                                               return __status;
                                                                           }

                                                                           __status = state.TrySetGlobal("add"u8);
                                                                           if (!__status.IsOk)
                                                                           {
                                                                               return __status;
                                                                           }

                                                                           __status = state.TryPushFunction(new global::CheatEngine.SDK.Lua.Callbacks.LuaNativeFunction(&__LuaThunk_greet));
                                                                           if (!__status.IsOk)
                                                                           {
                                                                               return __status;
                                                                           }

                                                                           __status = state.TrySetGlobal("greet"u8);
                                                                           if (!__status.IsOk)
                                                                           {
                                                                               return __status;
                                                                           }

                                                                           return global::CheatEngine.SDK.Lua.Calls.LuaStatus.Ok;
                                                                       }

                                                                       /// <summary>
                                                                       /// Assigns <c>nil</c> to every global that <see cref="RegisterLuaFunctions"/> registers: <c>add</c>, <c>greet</c>.
                                                                       /// Stack: +0 on success; +1 (the error value) on failure, as for every protected operation.
                                                                       /// </summary>
                                                                       /// <param name="state">The state to unregister from; the calling thread's.</param>
                                                                       /// <returns>The status of the first failing assignment, or <c>LuaStatus.Ok</c>.</returns>
                                                                       {{GeneratedCode}}
                                                                       public static global::CheatEngine.SDK.Lua.Calls.LuaStatus UnregisterLuaFunctions(global::CheatEngine.SDK.Lua.State.LuaState state)
                                                                       {
                                                                           global::CheatEngine.SDK.Lua.Calls.LuaStatus __status;
                                                                           state.PushNil();
                                                                           __status = state.TrySetGlobal("add"u8);
                                                                           if (!__status.IsOk)
                                                                           {
                                                                               return __status;
                                                                           }

                                                                           state.PushNil();
                                                                           __status = state.TrySetGlobal("greet"u8);
                                                                           if (!__status.IsOk)
                                                                           {
                                                                               return __status;
                                                                           }

                                                                           return global::CheatEngine.SDK.Lua.Calls.LuaStatus.Ok;
                                                                       }

                                                                       {{GeneratedCode}}
                                                                       [global::System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
                                                                       private static int __LuaThunk_add(nint __handle)
                                                                       {
                                                                           global::CheatEngine.SDK.Lua.State.LuaState __L = new(__handle);
                                                                           try
                                                                           {
                                                                               if (__L.Top != 2)
                                                                               {
                                                                                   return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.Fail(__L, "wrong number of arguments to 'add' (2 expected)"u8);
                                                                               }

                                                                               if (!global::CheatEngine.SDK.Lua.Marshalling.Int64Marshaller.TryRead(__L, 1, out long __arg0))
                                                                               {
                                                                                   return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.FailBadArgument(__L, 1, "integer"u8);
                                                                               }

                                                                               if (!global::CheatEngine.SDK.Lua.Marshalling.Int64Marshaller.TryRead(__L, 2, out long __arg1))
                                                                               {
                                                                                   return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.FailBadArgument(__L, 2, "integer"u8);
                                                                               }

                                                                               long __result = global::Demo.Functions.Add(__arg0, __arg1);
                                                                               global::CheatEngine.SDK.Lua.Marshalling.Int64Marshaller.Push(__L, __result);
                                                                               return 1;
                                                                           }
                                                                           catch (global::System.Exception __exception)
                                                                           {
                                                                               return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.Fail(__L, __exception);
                                                                           }
                                                                       }

                                                                       {{GeneratedCode}}
                                                                       [global::System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
                                                                       private static int __LuaThunk_greet(nint __handle)
                                                                       {
                                                                           global::CheatEngine.SDK.Lua.State.LuaState __L = new(__handle);
                                                                           try
                                                                           {
                                                                               if (__L.Top != 1)
                                                                               {
                                                                                   return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.Fail(__L, "wrong number of arguments to 'greet' (1 expected)"u8);
                                                                               }

                                                                               if (!global::CheatEngine.SDK.Lua.Marshalling.StringMarshaller.TryRead(__L, 1, out string? __arg0))
                                                                               {
                                                                                   return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.FailBadArgument(__L, 1, "string"u8);
                                                                               }

                                                                               string? __result = global::Demo.Functions.Greet(__arg0);
                                                                               global::CheatEngine.SDK.Lua.Marshalling.StringMarshaller.Push(__L, __result);
                                                                               return 1;
                                                                           }
                                                                           catch (global::System.Exception __exception)
                                                                           {
                                                                               return global::CheatEngine.SDK.Lua.Callbacks.LuaThunk.Fail(__L, __exception);
                                                                           }
                                                                       }
                                                                   }
                                                               }

                                                               """);

    private static readonly string GlobalsText = Normalise($$"""
                                                             // <auto-generated/>
                                                             #nullable enable

                                                             namespace Demo
                                                             {
                                                                 partial class Memory
                                                                 {
                                                                     {{GeneratedCode}}
                                                                     private static readonly global::CheatEngine.SDK.Lua.References.LuaRef s_luaGlobal_readInteger = new();

                                                                     {{GeneratedCode}}
                                                                     public static partial int ReadInt32(nuint address)
                                                                     {
                                                                         global::CheatEngine.SDK.Lua.State.LuaState __L = global::CheatEngine.SDK.Lua.Runtime.LuaRuntime.AcquireState();
                                                                         int __top = __L.Top;
                                                                         try
                                                                         {
                                                                             if (!global::CheatEngine.SDK.Lua.CompilerServices.LuaGlobalFunctions.TryPush(__L, s_luaGlobal_readInteger, "readInteger"u8))
                                                                             {
                                                                                 global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.ThrowUnresolvedGlobal(__L, __top, "readInteger");
                                                                             }

                                                                             global::CheatEngine.SDK.Lua.Marshalling.AddressMarshaller.Push(__L, address);
                                                                             global::CheatEngine.SDK.Lua.Calls.LuaStatus __status = __L.TryCall(1, 1);
                                                                             if (!__status.IsOk)
                                                                             {
                                                                                 global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.Throw(__L, __top, __status);
                                                                             }

                                                                             if (!global::CheatEngine.SDK.Lua.Marshalling.Int32Marshaller.TryRead(__L, -1, out int __result))
                                                                             {
                                                                                 global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.ThrowUnexpectedResult(__L, __top, -1, "readInteger", "an integer");
                                                                             }

                                                                             return __result;
                                                                         }
                                                                         finally
                                                                         {
                                                                             __L.SetTop(__top);
                                                                         }
                                                                     }

                                                                     {{GeneratedCode}}
                                                                     public static partial bool TryReadInt32(nuint address, out int value)
                                                                     {
                                                                         global::CheatEngine.SDK.Lua.State.LuaState __L = global::CheatEngine.SDK.Lua.Runtime.LuaRuntime.AcquireState();
                                                                         int __top = __L.Top;
                                                                         try
                                                                         {
                                                                             if (!global::CheatEngine.SDK.Lua.CompilerServices.LuaGlobalFunctions.TryPush(__L, s_luaGlobal_readInteger, "readInteger"u8))
                                                                             {
                                                                                 return global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.Fail(__L, __top, out value);
                                                                             }

                                                                             global::CheatEngine.SDK.Lua.Marshalling.AddressMarshaller.Push(__L, address);
                                                                             if (!__L.TryCall(1, 1).IsOk)
                                                                             {
                                                                                 return global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.Fail(__L, __top, out value);
                                                                             }

                                                                             bool __ok = global::CheatEngine.SDK.Lua.Marshalling.Int32Marshaller.TryRead(__L, -1, out value);
                                                                             return __ok;
                                                                         }
                                                                         catch (global::CheatEngine.SDK.Lua.Calls.LuaException)
                                                                         {
                                                                             value = default;
                                                                             return false;
                                                                         }
                                                                         finally
                                                                         {
                                                                             __L.SetTop(__top);
                                                                         }
                                                                     }
                                                                 }
                                                             }

                                                             """);

    /// <summary>
    ///     The file for <see cref="BindingSources.Functions" />: registration pair, then the thunks of <c>add</c> and
    ///     <c>greet</c>.
    /// </summary>
    public static string Functions()
    {
        return FunctionsText;
    }

    /// <summary>
    ///     The file for <see cref="BindingSources.Globals" />: one cache, the Try body, the throwing body.
    /// </summary>
    public static string Globals()
    {
        return GlobalsText;
    }

    private static string CreateGeneratedCodeLine()
    {
        var generator = typeof(LuaBindingsGenerator).Assembly.GetName();
        return $"[global::System.CodeDom.Compiler.GeneratedCode(\"{generator.Name}\", \"{generator.Version}\")]";
    }

    private static string Normalise(string text)
    {
        return text.Replace("\r\n", "\n", StringComparison.Ordinal);
    }
}
