using CheatEngine.SDK.SourceGenerators.Shared;

namespace CheatEngine.SDK.SourceGenerators.EntryPoint.Tests.SharedCode;

public sealed class GeneratedCodeTextTests
{
    [Fact]
    public void WriteFileHeader_starts_with_the_auto_generated_marker_then_enables_nullable()
    {
        SourceWriter writer = new();

        GeneratedCodeText.WriteFileHeader(writer);

        Assert.Equal("// <auto-generated/>\n#nullable enable\n\n", writer.ToString());
    }

    [Fact]
    public void CreateGeneratedCodeAttribute_names_the_generator_assembly_and_its_assembly_version()
    {
        var generator = typeof(EntryPointGenerator).Assembly.GetName();

        var attribute = GeneratedCodeText.CreateGeneratedCodeAttribute(typeof(EntryPointGenerator));

        Assert.Equal(
            $"[global::System.CodeDom.Compiler.GeneratedCode(\"CheatEngine.SDK.SourceGenerators.EntryPoint\", \"{generator.Version}\")]",
            attribute);
    }

    [Fact]
    public void CreateGeneratedCodeAttribute_version_is_stable_across_commits()
    {
        // MinVer keeps the ASSEMBLY version at major.0.0.0; only that keeps consumers' generated files from
        // changing with every build of the SDK.
        var version = typeof(EntryPointGenerator).Assembly.GetName().Version!;

        Assert.Equal(0, version.Minor);
        Assert.Equal(0, version.Build);
        Assert.Equal(0, version.Revision);
    }

    [Fact]
    public void Null_arguments_throw()
    {
        Assert.Throws<ArgumentNullException>(() => GeneratedCodeText.WriteFileHeader(null!));
        Assert.Throws<ArgumentNullException>(() => GeneratedCodeText.CreateGeneratedCodeAttribute(null!));
    }
}
