namespace CheatEngine.SDK.SourceGenerators.EntryPoint.Tests.Infrastructure;

/// <summary>
///     The exact text the generator must produce, written out independently of the emitter. Only the variable parts are
///     parameters; the tool name and version of <c>[GeneratedCode]</c> are read from the generator assembly (the version
///     follows the build, so it cannot be a literal here).
/// </summary>
internal static class ExpectedBootstrap
{
    public const string HintName = "CheatEngine.SDK.EntryPoint.g.cs";

    /// <param name="fullyQualifiedPluginType">For example <c>global::Demo.DemoPlugin</c>.</param>
    /// <param name="utf8NameLiteral">For example <c>"Demo Plugin"u8</c>.</param>
    /// <param name="factoryName">
    ///     Name of the file-local factory: <c>PluginFactory</c>, unless the plugin class itself is (or is nested in)
    ///     <c>CESDK.PluginFactory</c>.
    /// </param>
    /// <param name="declaredDiagnosticIds">
    ///     Comma-separated diagnostic IDs the plugin class declares through <c>[Experimental]</c> or
    ///     <c>[Obsolete(DiagnosticId = ...)]</c>; they get a second pragma line. Empty: no such line.
    /// </param>
    public static string Text(
        string fullyQualifiedPluginType,
        string utf8NameLiteral,
        string factoryName = "PluginFactory",
        string declaredDiagnosticIds = "")
    {
        var generator = typeof(EntryPointGenerator).Assembly.GetName();
        var tool = generator.Name!;
        var version = generator.Version!.ToString();
        var declaredIdsPragma = declaredDiagnosticIds.Length == 0
            ? string.Empty
            : $"#pragma warning disable {declaredDiagnosticIds} // declared by the plugin class: [Experimental] or [Obsolete(DiagnosticId = ...)]\n";

        var text = $$"""
                     // <auto-generated/>
                     #nullable enable

                     #pragma warning disable CS0612, CS0618 // the plugin class may be marked [Obsolete]
                     {{declaredIdsPragma}}
                     namespace CESDK
                     {
                         /// <summary>
                         /// Managed entry point of this plugin assembly. Cheat Engine looks up the type <c>CESDK.CESDK</c> and its
                         /// method <c>CEPluginInitialize</c> by name, in the plugin assembly itself: both names are imposed by the host.
                         /// </summary>
                         [global::System.CodeDom.Compiler.GeneratedCode("{{tool}}", "{{version}}")]
                         [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                         internal static class CESDK
                         {
                             /// <summary>
                             /// Called by the host, more than once per load. Forwards to the hosting runtime, which is idempotent, and never
                             /// lets an exception reach native code.
                             /// </summary>
                             /// <returns>1 on success, 0 on failure.</returns>
                             public static int CEPluginInitialize(global::System.IntPtr args, int size)
                             {
                                 try
                                 {
                                     return global::CheatEngine.SDK.Hosting.Bootstrap.PluginHost.InitializeManaged<{{factoryName}}>(args, size);
                                 }
                                 catch (global::System.Exception)
                                 {
                                     return 0;
                                 }
                             }
                         }

                         /// <summary>Constructs the plugin class without reflection and carries its display name as UTF-8.</summary>
                         [global::System.CodeDom.Compiler.GeneratedCode("{{tool}}", "{{version}}")]
                         [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                         file sealed class {{factoryName}} : global::CheatEngine.SDK.Hosting.Plugin.IPluginFactory
                         {
                             public static global::CheatEngine.SDK.Hosting.Plugin.CheatEnginePlugin Create() => new {{fullyQualifiedPluginType}}();

                             public static global::System.ReadOnlySpan<byte> Utf8Name => {{utf8NameLiteral}};
                         }
                     }

                     """;

        // The generator always writes '\n'; this file may be checked out with either line ending.
        return text.ReplaceLineEndings("\n");
    }
}
