using CheatEngine.SDK.SourceGenerators.EngineApi.Tests.Infrastructure;

namespace CheatEngine.SDK.SourceGenerators.EngineApi.Tests.Generator;

/// <summary>The generated text for the nominal spec file, and that it compiles clean against the real SDK.</summary>
public sealed class EmissionTests(RoslynFixture roslyn) : IClassFixture<RoslynFixture>
{
    [Fact]
    public void Nominal_spec_emits_one_file_with_the_namespace_type_cache_fields_and_four_wrappers()
    {
        var run = roslyn.Run("memory-scalars.cheatengine-sdk-api.txt", SpecSources.Memory);

        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;

        Assert.StartsWith("// <auto-generated/>\n#nullable enable\n", text, StringComparison.Ordinal);
        Assert.Contains("namespace Demo.Engine.Generated", text, StringComparison.Ordinal);
        Assert.Contains("public static partial class MemoryScalars", text, StringComparison.Ordinal);
        Assert.Contains(
            "private static readonly global::CheatEngine.SDK.Lua.References.LuaRef s_luaGlobal_readInteger = new();",
            text,
            StringComparison.Ordinal);
        Assert.Contains(
            "private static readonly global::CheatEngine.SDK.Lua.References.LuaRef s_luaGlobal_writeQword = new();",
            text,
            StringComparison.Ordinal);
        Assert.Contains(
            "CE &gt;= 7.7.0.10621; architecture: x64; thread: unknown; ownership: none; return: bool with out results; nil: absence; provenance: ExactInstalledFile: CE 7.7 celua.txt scalar memory globals.",
            text,
            StringComparison.Ordinal);

        // Every entry declares an 'address' argument, so each gets the two-method split (Emit/EngineApiFileEmitter.cs,
        // EmitAddressTypedWrapper): a private nuint core (LuaGlobalCallEmitter's own call shape, untouched) plus a
        // public wrapper typed with CheatEngine.SDK.Engine.Values.Address. A CE-side address is a ulong, not a nuint, so the
        // public surface never exposes the nuint-typed parameter.
        Assert.Contains("private static bool __TryReadInt32Raw(nuint address, out int value)", text,
            StringComparison.Ordinal);
        Assert.Contains(
            "public static bool TryReadInt32(global::CheatEngine.SDK.Engine.Values.Address address, out int value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("private static bool __TryReadInt64Raw(nuint address, out long value)", text,
            StringComparison.Ordinal);
        Assert.Contains(
            "public static bool TryReadInt64(global::CheatEngine.SDK.Engine.Values.Address address, out long value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("private static bool __WriteInt32Raw(nuint address, int value)", text,
            StringComparison.Ordinal);
        Assert.Contains(
            "public static bool WriteInt32(global::CheatEngine.SDK.Engine.Values.Address address, int value)", text,
            StringComparison.Ordinal);
        Assert.Contains("private static bool __WriteInt64Raw(nuint address, long value)", text,
            StringComparison.Ordinal);
        Assert.Contains(
            "public static bool WriteInt64(global::CheatEngine.SDK.Engine.Values.Address address, long value)", text,
            StringComparison.Ordinal);
        Assert.Contains(
            "[global::System.CodeDom.Compiler.GeneratedCode(\"CheatEngine.SDK.SourceGenerators.EngineApi\",", text,
            StringComparison.Ordinal);
        Assert.DoesNotContain("partial bool", text,
            StringComparison.Ordinal); // complete declarations, never a partial-method body
        Assert.Contains("global::CheatEngine.SDK.Lua.Marshalling.BooleanMarshaller.Push(__L, true);", text,
            StringComparison.Ordinal);
        Assert.Contains("if (!__L.TryCall(2, 1).IsOk)", text, StringComparison.Ordinal);
    }

    [Fact]
    public void The_try_form_body_matches_the_documented_call_shape_exactly()
    {
        var run = roslyn.Run("single.cheatengine-sdk-api.txt", SpecSources.SingleTry);
        run.AssertCompilesClean();

        // The private core: byte-for-byte the shape LuaGlobalCallEmitter produces, just renamed and
        // made private by EmitAddressTypedWrapper.
        var expectedCore = """
                           private static bool __TryReadInt32Raw(nuint address, out int value)
                           {
                               using global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation __operation = global::CheatEngine.SDK.Lua.Runtime.LuaRuntime.AcquireOperation();
                               global::CheatEngine.SDK.Lua.State.LuaState __L = __operation.State;
                               int __top = __L.Top;
                               try
                               {
                                   if (!global::CheatEngine.SDK.Lua.CompilerServices.LuaGlobalFunctions.TryPush(__L, s_luaGlobal_readInteger, "readInteger"u8))
                                   {
                                       return global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.Fail(__L, __top, out value);
                                   }

                                   global::CheatEngine.SDK.Lua.Marshalling.AddressMarshaller.Push(__L, address);
                                   if (!__L.TryCall(1, 1).IsOk)
                                   {
                                       return global::CheatEngine.SDK.Lua.CompilerServices.LuaCallSupport.Fail(__L, __top, out value);
                                   }

                                   bool __ok = global::CheatEngine.SDK.Lua.Marshalling.Int32Marshaller.TryRead(__L, -1, out value);
                                   return __ok;
                               }
                               catch (global::CheatEngine.SDK.Lua.Calls.LuaException)
                               {
                                   value = default;
                                   return false;
                               }
                               finally
                               {
                                   __L.SetTop(__top);
                               }
                           }
                           """;
        Assert.Contains(Indented(expectedCore), run.SingleGeneratedText, StringComparison.Ordinal);

        // The public wrapper: the only new code, a two-line boundary conversion.
        var expectedWrapper = """
                              public static bool TryReadInt32(global::CheatEngine.SDK.Engine.Values.Address address, out int value)
                              {
                                  return __TryReadInt32Raw(unchecked((nuint)address.ToUInt64()), out value);
                              }
                              """;
        Assert.Contains(Indented(expectedWrapper), run.SingleGeneratedText, StringComparison.Ordinal);
    }

    [Fact]
    public void Two_forms_of_the_same_global_declare_one_cache_field_and_two_methods()
    {
        var run = roslyn.Run("shared.cheatengine-sdk-api.txt", SpecSources.SharedGlobal);
        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;

        Assert.Equal(1, CountOccurrences(text, "s_luaGlobal_readInteger = new();"));
        Assert.Contains(
            "public static bool TryReadInt32(global::CheatEngine.SDK.Engine.Values.Address address, out int value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("public static int ReadInt32(global::CheatEngine.SDK.Engine.Values.Address address)", text,
            StringComparison.Ordinal);
    }

    [Fact]
    public void The_global_namespace_is_emitted_without_a_namespace_block()
    {
        const string Text = """
                            namespace:
                            type: Root

                            global: readInteger
                            method: TryReadInt32
                            form: try
                            arg: address:address
                            result: value:int32
                            doc: Reads an integer.
                            """;

        var run = roslyn.Run("root.cheatengine-sdk-api.txt", Text);
        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;

        Assert.DoesNotContain("namespace ", text, StringComparison.Ordinal);
        Assert.Contains("public static partial class Root", text, StringComparison.Ordinal);
    }

    /// <summary>Address Try results are public target addresses, not host-width integers.</summary>
    [Fact]
    public void An_address_try_result_is_exposed_as_Address_and_converted_from_the_raw_core()
    {
        const string Text =
            "namespace: Demo\ntype: Addresses\n\nglobal: getAddress\nmethod: TryGetAddress\nform: try\nresult: value:address\ndoc: Gets a target address.\n";

        var run = roslyn.Run("address-result.cheatengine-sdk-api.txt", Text);

        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;
        Assert.Contains("private static bool __TryGetAddressRaw(out nuint value)", text, StringComparison.Ordinal);
        Assert.Contains("public static bool TryGetAddress(out global::CheatEngine.SDK.Engine.Values.Address value)",
            text,
            StringComparison.Ordinal);
        Assert.Contains("nuint __engineApiRawResult0;", text, StringComparison.Ordinal);
        Assert.Contains(
            "value = new global::CheatEngine.SDK.Engine.Values.Address(unchecked((ulong)__engineApiRawResult0));",
            text, StringComparison.Ordinal);
    }

    /// <summary>Address throwing returns are public target addresses, not host-width integers.</summary>
    [Fact]
    public void An_address_throwing_return_is_exposed_as_Address_and_converted_from_the_raw_core()
    {
        const string Text =
            "namespace: Demo\ntype: Addresses\n\nglobal: getAddress\nmethod: GetAddress\nform: throwing\nreturn: address\ndoc: Gets a target address.\n";

        var run = roslyn.Run("address-return.cheatengine-sdk-api.txt", Text);

        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;
        Assert.Contains("private static nuint __GetAddressRaw()", text, StringComparison.Ordinal);
        Assert.Contains("public static global::CheatEngine.SDK.Engine.Values.Address GetAddress()", text,
            StringComparison.Ordinal);
        Assert.Contains(
            "return new global::CheatEngine.SDK.Engine.Values.Address(unchecked((ulong)__engineApiRawResult));",
            text, StringComparison.Ordinal);
        Assert.DoesNotContain("public static nuint", text, StringComparison.Ordinal);
    }

    /// <summary>Address arguments and results retain their strong target-address contract in the public signature.</summary>
    [Fact]
    public void Address_arguments_and_try_results_keep_the_complete_public_signature_strongly_typed()
    {
        const string Text =
            "namespace: Demo\ntype: Addresses\n\nglobal: resolvePointer\nmethod: TryResolvePointer\nform: try\narg: address:address\nresult: result:address\ndoc: Resolves a target pointer.\n";

        var run = roslyn.Run("address-argument-and-result.cheatengine-sdk-api.txt", Text);

        run.AssertCompilesClean();
        var text = run.SingleGeneratedText;
        Assert.Contains(
            "public static bool TryResolvePointer(global::CheatEngine.SDK.Engine.Values.Address address, out global::CheatEngine.SDK.Engine.Values.Address result)",
            text, StringComparison.Ordinal);
        Assert.DoesNotContain("public static bool TryResolvePointer(nuint", text, StringComparison.Ordinal);
        Assert.Contains("unchecked((nuint)address.ToUInt64())", text, StringComparison.Ordinal);
    }

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        var index = 0;
        while ((index = text.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }

        return count;
    }

    // The method sits two levels deep (namespace, then the partial class): 8 spaces, SourceWriter's convention.
    private static string Indented(string text)
    {
        return string.Join('\n',
            text.ReplaceLineEndings("\n").Split('\n')
                .Select(static line => line.Length > 0 ? "        " + line : line));
    }
}
