-- CheatEngine.SDK qualification driver (autorun). Generated by eng/qualification/Invoke-LocalQualification.ps1 from
-- eng/qualification/driver/zz_cesdk_qualification.template.lua into the SANDBOX copy's autorun folder only, and removed
-- by the runner when the run ends. It never runs from an installed Cheat Engine.
--
-- The driver is a recorder: it executes the scenario steps the runner generated, one per timer tick, and appends one
-- JSON event per line to the run's event file. It never judges a result; the runner evaluates the pass rule.
-- Every host call is protected with pcall. The driver is idempotent across a Lua state reset: it persists the index of
-- the last completed step and resumes after it when autorun loads it again.

local RUN = {
  id = __RUN_ID__,
  events = __EVENTS_PATH__,
  progress = __PROGRESS_PATH__,
  handshakeDir = __HANDSHAKE_DIR__,
  done = __DONE_PATH__,
  tickMs = 250,
}
local STEPS = __STEPS__
local BUNDLES = __BUNDLES__
local TARGETS = __TARGETS__

local function fileExists(path)
  local f = io.open(path, 'rb')
  if f == nil then return false end
  f:close()
  return true
end

local function readAll(path)
  local f = io.open(path, 'rb')
  if f == nil then return nil end
  local text = f:read('a')
  f:close()
  return text
end

local function milliseconds()
  local ok, ticks = pcall(getTickCount)
  if ok and math.type(ticks) == 'integer' then return ticks end
  return math.floor(os.clock() * 1000)
end

local T0 = milliseconds()

-- ---------------------------------------------------------------- JSON (strings, numbers, booleans, arrays, objects)
local ESCAPES = { ['"'] = '\\"', ['\\'] = '\\\\', ['\b'] = '\\b', ['\f'] = '\\f', ['\n'] = '\\n', ['\r'] = '\\r', ['\t'] = '\\t' }

local function jsonString(s)
  return '"' .. s:gsub('[%c"\\]', function(c) return ESCAPES[c] or string.format('\\u%04x', c:byte()) end) .. '"'
end

local encode
local function isArray(t)
  local count = 0
  for key in pairs(t) do
    if math.type(key) ~= 'integer' or key < 1 then return false end
    count = count + 1
  end
  for index = 1, count do
    if t[index] == nil then return false end
  end
  return true
end

encode = function(value)
  local kind = type(value)
  if value == nil then return 'null' end
  if kind == 'boolean' then return value and 'true' or 'false' end
  if kind == 'number' then
    if math.type(value) == 'integer' then return string.format('%d', value) end
    if value ~= value or value == math.huge or value == -math.huge then return jsonString(tostring(value)) end
    return string.format('%.17g', value)
  end
  if kind == 'string' then return jsonString(value) end
  if kind == 'table' then
    local parts = {}
    if isArray(value) then
      for index = 1, #value do parts[#parts + 1] = encode(value[index]) end
      return '[' .. table.concat(parts, ',') .. ']'
    end
    local keys = {}
    for key in pairs(value) do keys[#keys + 1] = tostring(key) end
    table.sort(keys)
    for _, key in ipairs(keys) do parts[#parts + 1] = jsonString(key) .. ':' .. encode(value[key]) end
    return '{' .. table.concat(parts, ',') .. '}'
  end
  return jsonString('<' .. kind .. '>')
end

-- ---------------------------------------------------------------- events and progress
local function emit(source, kind, message)
  local line = encode({ tMs = milliseconds() - T0, source = source, kind = kind, message = message })
  local f = io.open(RUN.events, 'ab')
  if f == nil then return false end
  f:write(line, '\n')
  f:close()
  return true
end

local function readProgress()
  local text = readAll(RUN.progress)
  if text == nil then return 0 end
  local runId, index = text:match('^(%S+)%s+(%d+)')
  if runId ~= RUN.id then return 0 end
  return tonumber(index)
end

local function writeProgress(index)
  local f = io.open(RUN.progress, 'wb')
  if f == nil then return end
  f:write(RUN.id, ' ', tostring(index))
  f:close()
end

-- A Lua value as a JSON-safe, type-tagged record, so nil, false, 0 and '' stay distinguishable.
local function describe(value)
  local kind = type(value)
  if kind == 'nil' then return { type = 'nil' } end
  if kind == 'string' or kind == 'boolean' then return { type = kind, value = value } end
  if kind == 'number' then return { type = math.type(value) or 'number', value = value } end
  return { type = kind, value = tostring(value) }
end

local function describeAll(packed, first)
  local values = {}
  for index = first, packed.n do values[#values + 1] = describe(packed[index]) end
  return values
end

-- ---------------------------------------------------------------- steps
local ACTIONS = {}

ACTIONS.openTarget = function(step)
  local pid = TARGETS[step.target]
  if pid == nil then return false, { describe('unknown target ' .. tostring(step.target)) } end
  local packed = table.pack(pcall(openProcess, pid))
  return packed[1], describeAll(packed, 2)
end

ACTIONS.loadPlugin = function(step)
  local path = BUNDLES[step.bundle]
  if path == nil then return false, { describe('unknown bundle ' .. tostring(step.bundle)) } end
  local packed = table.pack(pcall(loadPlugin, path))
  return packed[1], describeAll(packed, 2)
end

ACTIONS.call = function(step)
  local target = _G[step['function']]
  if type(target) ~= 'function' then
    return false, { describe('global ' .. step['function'] .. ' is ' .. type(target)) }
  end
  local packed = table.pack(pcall(target, table.unpack(step.args or {})))
  return packed[1], describeAll(packed, 2)
end

local state = { index = 0, waitUntil = nil, awaiting = false, finished = false, timer = nil }

local function finish(reason)
  if state.finished then return end
  state.finished = true
  emit('Driver', 'Completed', reason)
  local f = io.open(RUN.done, 'wb')
  if f ~= nil then f:write(RUN.id) f:close() end
  if state.timer ~= nil then
    pcall(function() state.timer.Enabled = false end)
  end
  pcall(closeCE)
end

local function runStep(index, step)
  if step.kind == 'Operator' then
    local handshake = RUN.handshakeDir .. '/step-' .. tostring(index) .. '.txt'
    if not state.awaiting then
      state.awaiting = true
      emit('Driver', 'AwaitOperator', encode({ step = index, id = step.id, instruction = step.instruction }))
      return false
    end
    local note = readAll(handshake)
    if note == nil then return false end
    state.awaiting = false
    emit('Operator', 'Observation', encode({ step = index, id = step.id, note = note }))
    return true
  end

  if step.action == 'wait' then
    if state.waitUntil == nil then
      state.waitUntil = milliseconds() + (step.ms or 0)
      return false
    end
    if milliseconds() < state.waitUntil then return false end
    state.waitUntil = nil
    emit('Driver', 'StepResult', encode({ step = index, id = step.id, action = 'wait', ok = true, values = {} }))
    return true
  end

  local action = ACTIONS[step.action]
  local ok, values
  if action == nil then
    ok, values = false, { describe('unknown action ' .. tostring(step.action)) }
  else
    local protected, first, second = pcall(action, step)
    if protected then ok, values = first, second else ok, values = false, { describe(first) } end
  end
  emit('Driver', 'StepResult', encode({ step = index, id = step.id, action = step.action, ok = ok, values = values }))
  return true
end

local function tick()
  if state.finished then return end
  local step = STEPS[state.index + 1]
  if step == nil then
    finish('all steps executed')
    return
  end
  local advanced = runStep(state.index + 1, step)
  if advanced then
    state.index = state.index + 1
    writeProgress(state.index)
  end
end

local function start()
  if fileExists(RUN.done) then return end
  state.index = readProgress()
  emit('Driver', state.index == 0 and 'Started' or 'Resumed',
    encode({ runId = RUN.id, step = state.index, inMainThread = (type(inMainThread) == 'function') and inMainThread() or nil }))
  local timer = createTimer(nil, false)
  timer.Interval = RUN.tickMs
  timer.OnTimer = function()
    local ok, failure = pcall(tick)
    if not ok then
      emit('Driver', 'DriverError', tostring(failure))
      finish('driver error')
    end
  end
  state.timer = timer
  timer.Enabled = true
end

local ok, failure = pcall(start)
if not ok then
  emit('Driver', 'DriverError', tostring(failure))
  pcall(closeCE)
end
