using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace CheatEngine.SDK.SourceGenerators.Shared;

/// <summary>
///     The fixed pieces every generated file starts with, so that all CheatEngine.SDK generators mark their output the
///     same way.
/// </summary>
/// <remarks>
///     <list type="bullet">
///         <item>
///             <description>
///                 <c>// &lt;auto-generated/&gt;</c> must be the first comment of the file: it is what makes the
///                 compiler, the IDE and analyzers treat the file as generated code.
///             </description>
///         </item>
///         <item>
///             <description>
///                 <c>#nullable enable</c> must follow: generated files start with the nullable context
///                 disabled, whatever the project says (otherwise annotations raise CS8669).
///             </description>
///         </item>
///         <item>
///             <description>
///                 <c>[GeneratedCode(tool, version)]</c> goes on every generated top-level type, with the
///                 generator's assembly name and assembly version.
///             </description>
///         </item>
///     </list>
/// </remarks>
[SuppressMessage(
	"Meziantou.Analyzer",
	"MA0182",
	Justification =
		"This shared internal helper is consumed by the designated friend generator and analyzer assemblies.")]
internal static class GeneratedCodeText
{
	/// <summary>First line of every generated file.</summary>
	public const string AutoGeneratedComment = "// <auto-generated/>";

	/// <summary>Second line of every generated file.</summary>
	public const string NullableEnable = "#nullable enable";

	/// <summary>Writes the two header lines followed by a blank line.</summary>
	public static void WriteFileHeader(SourceWriter writer)
	{
		if (writer is null)
		{
			throw new ArgumentNullException(nameof(writer));
		}

		writer.WriteLine(AutoGeneratedComment);
		writer.WriteLine(NullableEnable);
		writer.WriteLine();
	}

	/// <summary>
	///     Builds the <c>[global::System.CodeDom.Compiler.GeneratedCode("&lt;assembly&gt;", "&lt;version&gt;")]</c> line
	///     for the assembly that contains <paramref name="generatorType" />. Compute it once per generator (static
	///     field): it allocates an <see cref="AssemblyName" />.
	/// </summary>
	/// <remarks>
	///     The version is the <b>assembly</b> version (MinVer keeps it at <c>major.0.0.0</c>), not the informational
	///     version: the text must not change with every commit of the SDK, or every consumer would see its generated
	///     files churn on each package update.
	/// </remarks>
	public static string CreateGeneratedCodeAttribute(Type generatorType)
	{
		if (generatorType is null)
		{
			throw new ArgumentNullException(nameof(generatorType));
		}

		AssemblyName assembly = generatorType.Assembly.GetName();
		string version = (assembly.Version ?? new Version(0, 0, 0, 0)).ToString();
		return "[global::System.CodeDom.Compiler.GeneratedCode("
			   + CSharpLiteral.ToStringLiteral(assembly.Name ?? string.Empty)
			   + ", "
			   + CSharpLiteral.ToStringLiteral(version)
			   + ")]";
	}
}
