name: Pull request CI

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: CI
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci.yml
    with:
      collect-coverage: true
      dependency-review: ${{ vars.DEPENDENCY_REVIEW_ENABLED == 'true' }}
